import 'package:flagquiz/models/countrymodel.dart';

List<Countrymodel> list = [
  Countrymodel(
    code: "AD",
    names: {
      "en": "Andorra",
      "zh": "安道尔",
      "hi": "अंडोरा",
      "es": "Andorra",
      "fr": "Andorre",
      "ar": "أندورا",
      "tr": "Andorra",
    },
  ),
  Countrymodel(
    code: "AE",
    names: {
      "en": "United Arab Emirates",
      "zh": "阿拉伯联合酋长国",
      "hi": "संयुक्त अरब अमीरात",
      "es": "Emiratos Árabes Unidos",
      "fr": "Émirats arabes unis",
      "ar": "الإمارات العربية المتحدة",
      "tr": "Birleşik Arap Emirlikleri",
    },
  ),
  Countrymodel(
    code: "AF",
    names: {
      "en": "Afghanistan",
      "zh": "阿富汗",
      "hi": "अफ़गानिस्तान",
      "es": "Afganistán",
      "fr": "Afghanistan",
      "ar": "أفغانستان",
      "tr": "Afganistan",
    },
  ),
  Countrymodel(
    code: "AG",
    names: {
      "en": "Antigua and Barbuda",
      "zh": "安提瓜和巴布达",
      "hi": "एंटीगुआ और बारबुडा",
      "es": "Antigua y Barbuda",
      "fr": "Antigua-et-Barbuda",
      "ar": "أنتيغوا وباربودا",
      "tr": "Antigua ve Barbuda",
    },
  ),
  Countrymodel(
    code: "AI",
    names: {
      "en": "Anguilla",
      "zh": "安圭拉",
      "hi": "एंग्विला",
      "es": "Anguila",
      "fr": "Anguilla",
      "ar": "أنغويلا",
      "tr": "Anguilla",
    },
  ),
  Countrymodel(
    code: "AL",
    names: {
      "en": "Albania",
      "zh": "阿尔巴尼亚",
      "hi": "अल्बानिया",
      "es": "Albania",
      "fr": "Albanie",
      "ar": "ألبانيا",
      "tr": "Arnavutluk",
    },
  ),
  Countrymodel(
    code: "AM",
    names: {
      "en": "Armenia",
      "zh": "亚美尼亚",
      "hi": "आर्मेनिया",
      "es": "Armenia",
      "fr": "Arménie",
      "ar": "أرمينيا",
      "tr": "Ermenistan",
    },
  ),
  Countrymodel(
    code: "AO",
    names: {
      "en": "Angola",
      "zh": "安哥拉",
      "hi": "अंगोला",
      "es": "Angola",
      "fr": "Angola",
      "ar": "أنغولا",
      "tr": "Angola",
    },
  ),
  Countrymodel(
    code: "AQ",
    names: {
      "en": "Antarctica",
      "zh": "南极洲",
      "hi": "अंटार्कटिका",
      "es": "Antártida",
      "fr": "Antarctique",
      "ar": "القارة القطبية الجنوبية",
      "tr": "Antarktika",
    },
  ),
  Countrymodel(
    code: "AR",
    names: {
      "en": "Argentina",
      "zh": "阿根廷",
      "hi": "अर्जेंटीना",
      "es": "Argentina",
      "fr": "Argentine",
      "ar": "الأرجنتين",
      "tr": "Arjantin",
    },
  ),
  Countrymodel(
    code: "AS",
    names: {
      "en": "American Samoa",
      "zh": "美属萨摩亚",
      "hi": "अमेरिकी समोआ",
      "es": "Samoa Americana",
      "fr": "Samoa américaines",
      "ar": "ساموا الأمريكية",
      "tr": "Amerikan Samoası",
    },
  ),
  Countrymodel(
    code: "AT",
    names: {
      "en": "Austria",
      "zh": "奥地利",
      "hi": "ऑस्ट्रिया",
      "es": "Austria",
      "fr": "Autriche",
      "ar": "النمسا",
      "tr": "Avusturya",
    },
  ),
  Countrymodel(
    code: "AU",
    names: {
      "en": "Australia",
      "zh": "澳大利亚",
      "hi": "ऑस्ट्रेलिया",
      "es": "Australia",
      "fr": "Australie",
      "ar": "أستراليا",
      "tr": "Avustralya",
    },
  ),
  Countrymodel(
    code: "AW",
    names: {
      "en": "Aruba",
      "zh": "阿鲁巴",
      "hi": "अरूबा",
      "es": "Aruba",
      "fr": "Aruba",
      "ar": "أروبا",
      "tr": "Aruba",
    },
  ),
  Countrymodel(
    code: "AX",
    names: {
      "en": "Åland Islands",
      "zh": "奥兰群岛",
      "hi": "एलैंड द्वीपसमूह",
      "es": "Islas Åland",
      "fr": "Îles Åland",
      "ar": "جزر أولاند",
      "tr": "Åland Adaları",
    },
  ),
  Countrymodel(
    code: "AZ",
    names: {
      "en": "Azerbaijan",
      "zh": "阿塞拜疆",
      "hi": "अज़रबैजान",
      "es": "Azerbaiyán",
      "fr": "Azerbaïdjan",
      "ar": "أذربيجان",
      "tr": "Azerbaycan",
    },
  ),
  Countrymodel(
    code: "BA",
    names: {
      "en": "Bosnia and Herzegovina",
      "zh": "波斯尼亚和黑塞哥维那",
      "hi": "बोस्निया और हर्ज़ेगोविना",
      "es": "Bosnia y Herzegovina",
      "fr": "Bosnie-Herzégovine",
      "ar": "البوسنة والهرسك",
      "tr": "Bosna-Hersek",
    },
  ),
  Countrymodel(
    code: "BB",
    names: {
      "en": "Barbados",
      "zh": "巴巴多斯",
      "hi": "बारबाडोस",
      "es": "Barbados",
      "fr": "Barbade",
      "ar": "باربادوس",
      "tr": "Barbados",
    },
  ),
  Countrymodel(
    code: "BD",
    names: {
      "en": "Bangladesh",
      "zh": "孟加拉国",
      "hi": "बांग्लादेश",
      "es": "Bangladés",
      "fr": "Bangladesh",
      "ar": "بنغلاديش",
      "tr": "Bangladeş",
    },
  ),
  Countrymodel(
    code: "BE",
    names: {
      "en": "Belgium",
      "zh": "比利时",
      "hi": "बेल्जियम",
      "es": "Bélgica",
      "fr": "Belgique",
      "ar": "بلجيكا",
      "tr": "Belçika",
    },
  ),
  Countrymodel(
    code: "BF",
    names: {
      "en": "Burkina Faso",
      "zh": "布基纳法索",
      "hi": "बुर्किना फ़ासो",
      "es": "Burkina Faso",
      "fr": "Burkina Faso",
      "ar": "بوركينا فاسo",
      "tr": "Burkina Faso",
    },
  ),
  Countrymodel(
    code: "BG",
    names: {
      "en": "Bulgaria",
      "zh": "保加利亚",
      "hi": "बुल्गारिया",
      "es": "Bulgaria",
      "fr": "Bulgarie",
      "ar": "بلغاريا",
      "tr": "Bulgaristan",
    },
  ),
  Countrymodel(
    code: "BH",
    names: {
      "en": "Bahrain",
      "zh": "巴林",
      "hi": "बहरीन",
      "es": "Baréin",
      "fr": "Bahreïn",
      "ar": "البحرين",
      "tr": "Bahreyn",
    },
  ),
  Countrymodel(
    code: "BI",
    names: {
      "en": "Burundi",
      "zh": "布隆迪",
      "hi": "बुरुंडी",
      "es": "Burundi",
      "fr": "Burundi",
      "ar": "بوروندي",
      "tr": "Burundi",
    },
  ),
  Countrymodel(
    code: "BJ",
    names: {
      "en": "Benin",
      "zh": "贝宁",
      "hi": "बेनिन",
      "es": "Benín",
      "fr": "Bénin",
      "ar": "بنين",
      "tr": "Benin",
    },
  ),
  Countrymodel(
    code: "BL",
    names: {
      "en": "Saint Barthélemy",
      "zh": "圣巴泰勒米",
      "hi": "सेंट बार्थेलेमी",
      "es": "San Bartolomé",
      "fr": "Saint-Barthélemy",
      "ar": "سان بارتيلمي",
      "tr": "Saint Barthélemy",
    },
  ),
  Countrymodel(
    code: "BM",
    names: {
      "en": "Bermuda",
      "zh": "百慕大",
      "hi": "बरमूडा",
      "es": "Bermudas",
      "fr": "Bermudes",
      "ar": "برمودا",
      "tr": "Bermuda",
    },
  ),
  Countrymodel(
    code: "BN",
    names: {
      "en": "Brunei Darussalam",
      "zh": "文莱达鲁萨兰国",
      "hi": "ब्रूनेई",
      "es": "Brunéi",
      "fr": "Brunéi Darussalam",
      "ar": "بروناي",
      "tr": "Brunei",
    },
  ),
  Countrymodel(
    code: "BO",
    names: {
      "en": "Bolivia (Plurinational State of)",
      "zh": "玻利维亚",
      "hi": "बोलीविया",
      "es": "Bolivia",
      "fr": "Bolivie",
      "ar": "بوليفيا",
      "tr": "Bolivya",
    },
  ),
  Countrymodel(
    code: "BQ",
    names: {
      "en": "Bonaire, Sint Eustatius and Saba",
      "zh": "博奈尔、圣尤斯特歇斯和萨巴",
      "hi": "बोनेयर, सिंट युस्टेटियस और सaba",
      "es": "Bonaire, San Eustaquio y Saba",
      "fr": "Pays-Bas caribéens",
      "ar": "الجزر الكاريبية الهولندية",
      "tr": "Karayip Hollandası",
    },
  ),
  Countrymodel(
    code: "BR",
    names: {
      "en": "Brazil",
      "zh": "巴西",
      "hi": "ब्राज़ील",
      "es": "Brasil",
      "fr": "Brésil",
      "ar": "البرازيل",
      "tr": "Brezilya",
    },
  ),
  Countrymodel(
    code: "BS",
    names: {
      "en": "Bahamas",
      "zh": "巴哈马",
      "hi": "बहामास",
      "es": "Bahamas",
      "fr": "Bahamas",
      "ar": "باهاماس",
      "tr": "Bahamalar",
    },
  ),
  Countrymodel(
    code: "BT",
    names: {
      "en": "Bhutan",
      "zh": "不丹",
      "hi": "भूटान",
      "es": "Bután",
      "fr": "Bhoutan",
      "ar": "بوتان",
      "tr": "Butan",
    },
  ),
  Countrymodel(
    code: "BV",
    names: {
      "en": "Bouvet Island",
      "zh": "布韦岛",
      "hi": "बौवेट द्वीप",
      "es": "Isla Bouvet",
      "fr": "Île Bouvet",
      "ar": "جزيرة بوفيه",
      "tr": "Bouvet Adası",
    },
  ),
  Countrymodel(
    code: "BW",
    names: {
      "en": "Botswana",
      "zh": "博茨瓦纳",
      "hi": "बोत्सवाना",
      "es": "Botsuana",
      "fr": "Botswana",
      "ar": "بوتسوانا",
      "tr": "Botsvana",
    },
  ),
  Countrymodel(
    code: "BY",
    names: {
      "en": "Belarus",
      "zh": "白俄罗斯",
      "hi": "बेलारूस",
      "es": "Bielorrusia",
      "fr": "Biélorussie",
      "ar": "بيلاروس",
      "tr": "Belarus",
    },
  ),
  Countrymodel(
    code: "BZ",
    names: {
      "en": "Belize",
      "zh": "伯利兹",
      "hi": "बेलीज़",
      "es": "Belice",
      "fr": "Belize",
      "ar": "بليز",
      "tr": "Belize",
    },
  ),
  Countrymodel(
    code: "CA",
    names: {
      "en": "Canada",
      "zh": "加拿大",
      "hi": "कनाडा",
      "es": "Canadá",
      "fr": "Canada",
      "ar": "كندا",
      "tr": "Kanada",
    },
  ),
  Countrymodel(
    code: "CC",
    names: {
      "en": "Cocos (Keeling) Islands",
      "zh": "科科斯（基林）群岛",
      "hi": "कोकोस (कीलिंग) द्वीपसमूह",
      "es": "Islas Cocos (Keeling)",
      "fr": "Îles Cocos",
      "ar": "جزر كوكوس (كيلينغ)",
      "tr": "Cocos (Keeling) Adaları",
    },
  ),
  Countrymodel(
    code: "CD",
    names: {
      "en": "Congo, Democratic Republic of the",
      "zh": "刚果民主共和国",
      "hi": "कांगो लोकतांत्रिक गणराज्य",
      "es": "República Democrática del Congo",
      "fr": "Congo (Rép. dém.)",
      "ar": "جمهورية الكونغو الديمقراطية",
      "tr": "Kongo Demokratik Cumhuriyeti",
    },
  ),
  Countrymodel(
    code: "CF",
    names: {
      "en": "Central African Republic",
      "zh": "中非共和国",
      "hi": "मध्य अफ़्रीकी गणराज्य",
      "es": "República Centroafricana",
      "fr": "République centrafricaine",
      "ar": "جمهورية أفريقيا الوسطى",
      "tr": "Orta Afrika Cumhuriyeti",
    },
  ),
  Countrymodel(
    code: "CG",
    names: {
      "en": "Congo",
      "zh": "刚果共和国",
      "hi": "कांगो गणराज्य",
      "es": "Congo",
      "fr": "Congo",
      "ar": "جمهورية الكونغو",
      "tr": "Kongo Cumhuriyeti",
    },
  ),
  Countrymodel(
    code: "CH",
    names: {
      "en": "Switzerland",
      "zh": "瑞士",
      "hi": "स्विट्ज़रलैंड",
      "es": "Suiza",
      "fr": "Suisse",
      "ar": "سويسرا",
      "tr": "İsviçre",
    },
  ),
  Countrymodel(
    code: "CI",
    names: {
      "en": "Côte d'Ivoire",
      "zh": "科特迪瓦",
      "hi": "कोट डी आइवर",
      "es": "Costa de Marfil",
      "fr": "Côte d'Ivoire",
      "ar": "كوت ديفوار",
      "tr": "Fildişi Sahili",
    },
  ),
  Countrymodel(
    code: "CK",
    names: {
      "en": "Cook Islands",
      "zh": "库克群岛",
      "hi": "कुक द्वीपसमूह",
      "es": "Islas Cook",
      "fr": "Îles Cook",
      "ar": "جزر كوك",
      "tr": "Cook Adaları",
    },
  ),
  Countrymodel(
    code: "CL",
    names: {
      "en": "Chile",
      "zh": "智利",
      "hi": "चिली",
      "es": "Chile",
      "fr": "Chili",
      "ar": "تشيلي",
      "tr": "Şili",
    },
  ),
  Countrymodel(
    code: "CM",
    names: {
      "en": "Cameroon",
      "zh": "喀麦隆",
      "hi": "कैमरून",
      "es": "Camerún",
      "fr": "Cameroun",
      "ar": "الكاميرون",
      "tr": "Kamerun",
    },
  ),
  Countrymodel(
    code: "CN",
    names: {
      "en": "China",
      "zh": "中国",
      "hi": "चीन",
      "es": "China",
      "fr": "Chine",
      "ar": "الصين",
      "tr": "Çin",
    },
  ),
  Countrymodel(
    code: "CO",
    names: {
      "en": "Colombia",
      "zh": "哥伦比亚",
      "hi": "कोलंबिया",
      "es": "Colombia",
      "fr": "Colombie",
      "ar": "كولومبia",
      "tr": "Kolombiya",
    },
  ),
  Countrymodel(
    code: "CR",
    names: {
      "en": "Costa Rica",
      "zh": "哥斯达黎加",
      "hi": "कोस्टा रिका",
      "es": "Costa Rica",
      "fr": "Costa Rica",
      "ar": "كوستاريكا",
      "tr": "Kosta Rika",
    },
  ),
  Countrymodel(
    code: "CU",
    names: {
      "en": "Cuba",
      "zh": "古巴",
      "hi": "क्यूबा",
      "es": "Cuba",
      "fr": "Cuba",
      "ar": "كوبا",
      "tr": "Küba",
    },
  ),
  Countrymodel(
    code: "CV",
    names: {
      "en": "Cabo Verde",
      "zh": "佛得角",
      "hi": "केप वर्ड",
      "es": "Cabo Verde",
      "fr": "Cap-Vert",
      "ar": "الرأس الأخضر",
      "tr": "Cape Verde",
    },
  ),
  Countrymodel(
    code: "CW",
    names: {
      "en": "Curaçao",
      "zh": "库拉索",
      "hi": "कुराकाओ",
      "es": "Curazao",
      "fr": "Curaçao",
      "ar": "كوراساو",
      "tr": "Curaçao",
    },
  ),
  Countrymodel(
    code: "CX",
    names: {
      "en": "Christmas Island",
      "zh": "圣诞岛",
      "hi": "क्रिसमस द्वीप",
      "es": "Isla de Navidad",
      "fr": "Île Christmas",
      "ar": "جزيرة الكريسماس",
      "tr": "Christmas Adası",
    },
  ),
  Countrymodel(
    code: "CY",
    names: {
      "en": "Cyprus",
      "zh": "塞浦路斯",
      "hi": "साइप्रस",
      "es": "Chipre",
      "fr": "Chypre",
      "ar": "قبرص",
      "tr": "Kıbrıs",
    },
  ),
  Countrymodel(
    code: "CZ",
    names: {
      "en": "Czechia",
      "zh": "捷克",
      "hi": "चेकिया",
      "es": "Chequia",
      "fr": "Tchéquie",
      "ar": "التشيك",
      "tr": "Çekya",
    },
  ),
  Countrymodel(
    code: "DE",
    names: {
      "en": "Germany",
      "zh": "德国",
      "hi": "जर्मनी",
      "es": "Alemania",
      "fr": "Allemagne",
      "ar": "ألمانيا",
      "tr": "Almanya",
    },
  ),
  Countrymodel(
    code: "DJ",
    names: {
      "en": "Djibouti",
      "zh": "吉布提",
      "hi": "जिबूती",
      "es": "Yibuti",
      "fr": "Djibouti",
      "ar": "جيبوتي",
      "tr": "Cibuti",
    },
  ),
  Countrymodel(
    code: "DK",
    names: {
      "en": "Denmark",
      "zh": "丹麦",
      "hi": "डेनमार्क",
      "es": "Dinamarca",
      "fr": "Danemark",
      "ar": "الدانمرك",
      "tr": "Danimarka",
    },
  ),
  Countrymodel(
    code: "DM",
    names: {
      "en": "Dominica",
      "zh": "多米尼克",
      "hi": "डोमिनिका",
      "es": "Dominica",
      "fr": "Dominique",
      "ar": "دومينيكا",
      "tr": "Dominika",
    },
  ),
  Countrymodel(
    code: "DO",
    names: {
      "en": "Dominican Republic",
      "zh": "多米尼加共和国",
      "hi": "डोमिनिकन गणराज्य",
      "es": "República Dominicana",
      "fr": "République dominicaine",
      "ar": "جمهورية الدومينيكان",
      "tr": "Dominik Cumhuriyeti",
    },
  ),
  Countrymodel(
    code: "DZ",
    names: {
      "en": "Algeria",
      "zh": "阿尔及利亚",
      "hi": "अल्जीरिया",
      "es": "Argelia",
      "fr": "Algérie",
      "ar": "الجزائر",
      "tr": "Cezayir",
    },
  ),
  Countrymodel(
    code: "EC",
    names: {
      "en": "Ecuador",
      "zh": "厄瓜多尔",
      "hi": "इक्वाडोर",
      "es": "Ecuador",
      "fr": "Équateur",
      "ar": "الإكوادور",
      "tr": "Ekvador",
    },
  ),
  Countrymodel(
    code: "EE",
    names: {
      "en": "Estonia",
      "zh": "爱沙尼亚",
      "hi": "एस्तोनिया",
      "es": "Estonia",
      "fr": "Estonie",
      "ar": "إستونيا",
      "tr": "Estonya",
    },
  ),
  Countrymodel(
    code: "EG",
    names: {
      "en": "Egypt",
      "zh": "埃及",
      "hi": "मिस्र",
      "es": "Egipto",
      "fr": "Égypte",
      "ar": "مصر",
      "tr": "Mısır",
    },
  ),
  Countrymodel(
    code: "EH",
    names: {
      "en": "Western Sahara",
      "zh": "西撒哈拉",
      "hi": "पश्चिमी सहारा",
      "es": "Sahara Occidental",
      "fr": "Sahara occidental",
      "ar": "الصحراء الغربية",
      "tr": "Batı Sahra",
    },
  ),
  Countrymodel(
    code: "ER",
    names: {
      "en": "Eritrea",
      "zh": "厄立特里亚",
      "hi": "इरिट्रिया",
      "es": "Eritrea",
      "fr": "Érythrée",
      "ar": "إريتريا",
      "tr": "Eritre",
    },
  ),
  Countrymodel(
    code: "ES",
    names: {
      "en": "Spain",
      "zh": "西班牙",
      "hi": "स्पेन",
      "es": "España",
      "fr": "Espagne",
      "ar": "إسبانيا",
      "tr": "İspanya",
    },
  ),
  Countrymodel(
    code: "ET",
    names: {
      "en": "Ethiopia",
      "zh": "埃塞俄比亚",
      "hi": "इथियोपिया",
      "es": "Etiopía",
      "fr": "Éthiopie",
      "ar": "إثيوبيا",
      "tr": "Etiyopya",
    },
  ),
  Countrymodel(
    code: "FI",
    names: {
      "en": "Finland",
      "zh": "芬兰",
      "hi": "फ़िनलैंड",
      "es": "Finlandia",
      "fr": "Finlande",
      "ar": "فنلندا",
      "tr": "Finlandiya",
    },
  ),
  Countrymodel(
    code: "FJ",
    names: {
      "en": "Fiji",
      "zh": "斐济",
      "hi": "फ़िजी",
      "es": "Fiyi",
      "fr": "Fidji",
      "ar": "فيجي",
      "tr": "Fiji",
    },
  ),
  Countrymodel(
    code: "FK",
    names: {
      "en": "Falkland Islands (Malvinas)",
      "zh": "福克兰群岛（马尔维纳斯）",
      "hi": "फ़ॉकलैंड द्वीपसमूह",
      "es": "Islas Malvinas (Falkland)",
      "fr": "Îles Malouines",
      "ar": "جزر فوكلاند",
      "tr": "Falkland Adaları",
    },
  ),
  Countrymodel(
    code: "FM",
    names: {
      "en": "Micronesia (Federated States of)",
      "zh": "密克罗尼西亚联邦",
      "hi": "माइक्रोनेशिया",
      "es": "Micronesia",
      "fr": "Micronésie",
      "ar": "ميكرونيزيا",
      "tr": "Mikronezya",
    },
  ),
  Countrymodel(
    code: "FO",
    names: {
      "en": "Faroe Islands",
      "zh": "法罗群岛",
      "hi": "फ़ेरो द्वीपसमूह",
      "es": "Islas Feroe",
      "fr": "Îles Féroé",
      "ar": "جزر فارو",
      "tr": "Faroe Adaları",
    },
  ),
  Countrymodel(
    code: "FR",
    names: {
      "en": "France",
      "zh": "法国",
      "hi": "फ़्रांस",
      "es": "Francia",
      "fr": "France",
      "ar": "فرنسا",
      "tr": "Fransa",
    },
  ),
  Countrymodel(
    code: "GA",
    names: {
      "en": "Gabon",
      "zh": "加蓬",
      "hi": "गैबॉन",
      "es": "Gabón",
      "fr": "Gabon",
      "ar": "الغابون",
      "tr": "Gabon",
    },
  ),
  Countrymodel(
    code: "GB",
    names: {
      "en": "United Kingdom of Great Britain and Northern Ireland",
      "zh": "英国",
      "hi": "यूनाइटेड किंगडम",
      "es": "Reino Unido",
      "fr": "Royaume-Uni",
      "ar": "المملكة المتحدة",
      "tr": "Birleşik Krallık",
    },
  ),
  Countrymodel(
    code: "GD",
    names: {
      "en": "Grenada",
      "zh": "格林纳达",
      "hi": "ग्रेनेडा",
      "es": "Grenada",
      "fr": "Grenade",
      "ar": "غرينادا",
      "tr": "Grenada",
    },
  ),
  Countrymodel(
    code: "GE",
    names: {
      "en": "Georgia",
      "zh": "格鲁吉亚",
      "hi": "जॉर्जिया",
      "es": "Georgia",
      "fr": "Géorgie",
      "ar": "جورجيا",
      "tr": "Gürcistan",
    },
  ),
  Countrymodel(
    code: "GF",
    names: {
      "en": "French Guiana",
      "zh": "法属圭亚那",
      "hi": "फ़्रेंच गयाना",
      "es": "Guayana Francesa",
      "fr": "Guyane française",
      "ar": "غويانا الفرنسية",
      "tr": "Fransız Guyanası",
    },
  ),
  Countrymodel(
    code: "GG",
    names: {
      "en": "Guernsey",
      "zh": "根西岛",
      "hi": "ग्वेर्नसे",
      "es": "Guernsey",
      "fr": "Guernesey",
      "ar": "غيرنزي",
      "tr": "Guernsey",
    },
  ),
  Countrymodel(
    code: "GH",
    names: {
      "en": "Ghana",
      "zh": "加纳",
      "hi": "घाना",
      "es": "Ghana",
      "fr": "Ghana",
      "ar": "غانا",
      "tr": "Gana",
    },
  ),
  Countrymodel(
    code: "GI",
    names: {
      "en": "Gibraltar",
      "zh": "直布罗陀",
      "hi": "जिब्राल्टर",
      "es": "Gibraltar",
      "fr": "Gibraltar",
      "ar": "جبل طارق",
      "tr": "Cebelitarık",
    },
  ),
  Countrymodel(
    code: "GL",
    names: {
      "en": "Greenland",
      "zh": "格陵兰",
      "hi": "ग्रीनलैंड",
      "es": "Groenlandia",
      "fr": "Groenland",
      "ar": "غرينلاند",
      "tr": "Grönland",
    },
  ),
  Countrymodel(
    code: "GM",
    names: {
      "en": "Gambia",
      "zh": "冈比亚",
      "hi": "गाम्बिया",
      "es": "Gambia",
      "fr": "Gambie",
      "ar": "غامبيا",
      "tr": "Gambiya",
    },
  ),
  Countrymodel(
    code: "GN",
    names: {
      "en": "Guinea",
      "zh": "几内亚",
      "hi": "गिनी",
      "es": "Guinea",
      "fr": "Guinée",
      "ar": "غينيا",
      "tr": "Gine",
    },
  ),
  Countrymodel(
    code: "GP",
    names: {
      "en": "Guadeloupe",
      "zh": "瓜德罗普",
      "hi": "ग्वाडेलूप",
      "es": "Guadalupe",
      "fr": "Guadeloupe",
      "ar": "غوادلوب",
      "tr": "Guadeloupe",
    },
  ),
  Countrymodel(
    code: "GQ",
    names: {
      "en": "Equatorial Guinea",
      "zh": "赤道几内亚",
      "hi": "इक्वेटोरियल गिनी",
      "es": "Guinea Ecuatorial",
      "fr": "Guinée équatoriale",
      "ar": "غينيا الاستوائية",
      "tr": "Ekvator Ginesi",
    },
  ),
  Countrymodel(
    code: "GR",
    names: {
      "en": "Greece",
      "zh": "希腊",
      "hi": "यूनान",
      "es": "Grecia",
      "fr": "Grèce",
      "ar": "اليونان",
      "tr": "Yunanistan",
    },
  ),
  Countrymodel(
    code: "GS",
    names: {
      "en": "South Georgia and the South Sandwich Islands",
      "zh": "南乔治亚岛和南桑威奇群岛",
      "hi": "दक्षिण जॉर्जिया और दक्षिण सैंडविच द्वीपसमूह",
      "es": "Islas Georgias del Sur y Sandwich del Sur",
      "fr": "Géorgie du Sud-et-les Îles Sandwich du Sud",
      "ar": "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
      "tr": "Güney Georgia ve Güney Sandwich Adaları",
    },
  ),
  Countrymodel(
    code: "GT",
    names: {
      "en": "Guatemala",
      "zh": "危地马拉",
      "hi": "ग्वाटेमाला",
      "es": "Guatemala",
      "fr": "Guatemala",
      "ar": "غواتيمالا",
      "tr": "Guatemala",
    },
  ),
  Countrymodel(
    code: "GU",
    names: {
      "en": "Guam",
      "zh": "关岛",
      "hi": "गुआम",
      "es": "Guam",
      "fr": "Guam",
      "ar": "غوام",
      "tr": "Guam",
    },
  ),
  Countrymodel(
    code: "GW",
    names: {
      "en": "Guinea-Bissau",
      "zh": "几内亚比绍",
      "hi": "गिनी-बिसाऊ",
      "es": "Guinea-Bisáu",
      "fr": "Guinée-Bissau",
      "ar": "غينيا بيساو",
      "tr": "Gine-Bissau",
    },
  ),
  Countrymodel(
    code: "GY",
    names: {
      "en": "Guyana",
      "zh": "圭亚那",
      "hi": "गयाना",
      "es": "Guyana",
      "fr": "Guyane",
      "ar": "غيانا",
      "tr": "Guyana",
    },
  ),
  Countrymodel(
    code: "HK",
    names: {
      "en": "Hong Kong",
      "zh": "香港",
      "hi": "हांगकांग",
      "es": "Hong Kong",
      "fr": "Hong Kong",
      "ar": "هونغ كونغ",
      "tr": "Hong Kong",
    },
  ),
  Countrymodel(
    code: "HM",
    names: {
      "en": "Heard Island and McDonald Islands",
      "zh": "赫德岛和麦克唐纳群岛",
      "hi": "हर्ड द्वीप और मैकडोनाल्ड द्वीपसमूह",
      "es": "Islas Heard y McDonald",
      "fr": "Îles Heard-et-MacDonald",
      "ar": "جزيرة هيرد وجزر ماكدونالد",
      "tr": "Heard Adası ve McDonald Adaları",
    },
  ),
  Countrymodel(
    code: "HN",
    names: {
      "en": "Honduras",
      "zh": "洪都拉斯",
      "hi": "होंडुरास",
      "es": "Honduras",
      "fr": "Honduras",
      "ar": "هندوراس",
      "tr": "Honduras",
    },
  ),
  Countrymodel(
    code: "HR",
    names: {
      "en": "Croatia",
      "zh": "克罗地亚",
      "hi": "क्रोएशिया",
      "es": "Croacia",
      "fr": "Croatie",
      "ar": "كرواتيا",
      "tr": "Hırvatistan",
    },
  ),
  Countrymodel(
    code: "HT",
    names: {
      "en": "Haiti",
      "zh": "海地",
      "hi": "हाइती",
      "es": "Haití",
      "fr": "Haïti",
      "ar": "هايتي",
      "tr": "Haiti",
    },
  ),
  Countrymodel(
    code: "HU",
    names: {
      "en": "Hungary",
      "zh": "匈牙利",
      "hi": "हंगरी",
      "es": "Hungría",
      "fr": "Hongrie",
      "ar": "المجر",
      "tr": "Macaristan",
    },
  ),
  Countrymodel(
    code: "ID",
    names: {
      "en": "Indonesia",
      "zh": "印度尼西亚",
      "hi": "इंडोनेशिया",
      "es": "Indonesia",
      "fr": "Indonésie",
      "ar": "إندونيسيا",
      "tr": "Endonezya",
    },
  ),
  Countrymodel(
    code: "IE",
    names: {
      "en": "Ireland",
      "zh": "爱尔兰",
      "hi": "आयरलैंड",
      "es": "Irlanda",
      "fr": "Irlande",
      "ar": "أيرلندا",
      "tr": "İrlanda",
    },
  ),
  Countrymodel(
    code: "IL",
    names: {
      "en": "Israel",
      "zh": "以色列",
      "hi": "इज़राइल",
      "es": "Israel",
      "fr": "Israël",
      "ar": "إسرائيل",
      "tr": "İsrail",
    },
  ),
  Countrymodel(
    code: "IM",
    names: {
      "en": "Isle of Man",
      "zh": "马恩岛",
      "hi": "आइल ऑफ़ मैन",
      "es": "Isla de Man",
      "fr": "Île de Man",
      "ar": "جزيرة مان",
      "tr": "Man Adası",
    },
  ),
  Countrymodel(
    code: "IN",
    names: {
      "en": "India",
      "zh": "印度",
      "hi": "भारत",
      "es": "India",
      "fr": "Inde",
      "ar": "الهند",
      "tr": "Hindistan",
    },
  ),
  Countrymodel(
    code: "IO",
    names: {
      "en": "British Indian Ocean Territory",
      "zh": "英属印度洋领地",
      "hi": "ब्रिटिश हिंद महासागरीय क्षेत्र",
      "es": "Territorio Británico del Océano Índico",
      "fr": "Territoire britannique de l'océan Indien",
      "ar": "إقليم المحيط الهندي البريطاني",
      "tr": "Britanya Hint Okyanusu Toprakları",
    },
  ),
  Countrymodel(
    code: "IQ",
    names: {
      "en": "Iraq",
      "zh": "伊拉克",
      "hi": "इराक",
      "es": "Irak",
      "fr": "Irak",
      "ar": "العراق",
      "tr": "Irak",
    },
  ),
  Countrymodel(
    code: "IR",
    names: {
      "en": "Iran (Islamic Republic of)",
      "zh": "伊朗",
      "hi": "ईरान",
      "es": "Irán",
      "fr": "Iran",
      "ar": "إيران",
      "tr": "İran",
    },
  ),
  Countrymodel(
    code: "IS",
    names: {
      "en": "Iceland",
      "zh": "冰岛",
      "hi": "आइसलैंड",
      "es": "Islandia",
      "fr": "Islande",
      "ar": "آيسلندا",
      "tr": "İzlanda",
    },
  ),
  Countrymodel(
    code: "IT",
    names: {
      "en": "Italy",
      "zh": "意大利",
      "hi": "इटली",
      "es": "Italia",
      "fr": "Italie",
      "ar": "إيطاليا",
      "tr": "İtalya",
    },
  ),
  Countrymodel(
    code: "JE",
    names: {
      "en": "Jersey",
      "zh": "泽西岛",
      "hi": "जर्सी",
      "es": "Jersey",
      "fr": "Jersey",
      "ar": "جيرسي",
      "tr": "Jersey",
    },
  ),
  Countrymodel(
    code: "JM",
    names: {
      "en": "Jamaica",
      "zh": "牙买加",
      "hi": "जमैका",
      "es": "Jamaica",
      "fr": "Jamaïque",
      "ar": "جامايكا",
      "tr": "Jamaika",
    },
  ),
  Countrymodel(
    code: "JO",
    names: {
      "en": "Jordan",
      "zh": "约旦",
      "hi": "जॉर्डन",
      "es": "Jordania",
      "fr": "Jordanie",
      "ar": "الأردن",
      "tr": "Ürdün",
    },
  ),
  Countrymodel(
    code: "JP",
    names: {
      "en": "Japan",
      "zh": "日本",
      "hi": "जापान",
      "es": "Japón",
      "fr": "Japon",
      "ar": "اليابان",
      "tr": "Japonya",
    },
  ),
  Countrymodel(
    code: "KE",
    names: {
      "en": "Kenya",
      "zh": "肯尼亚",
      "hi": "केन्या",
      "es": "Kenia",
      "fr": "Kenya",
      "ar": "كينيا",
      "tr": "Kenya",
    },
  ),
  Countrymodel(
    code: "KG",
    names: {
      "en": "Kyrgyzstan",
      "zh": "吉尔吉斯斯坦",
      "hi": "किर्गिज़स्तान",
      "es": "Kirguistán",
      "fr": "Kirghizistan",
      "ar": "قيرغيزستان",
      "tr": "Kırgızistan",
    },
  ),
  Countrymodel(
    code: "KH",
    names: {
      "en": "Cambodia",
      "zh": "柬埔寨",
      "hi": "कंबोडिया",
      "es": "Camboya",
      "fr": "Cambodge",
      "ar": "كمبوديا",
      "tr": "Kamboçya",
    },
  ),
  Countrymodel(
    code: "KI",
    names: {
      "en": "Kiribati",
      "zh": "基里巴斯",
      "hi": "किरिबाती",
      "es": "Kiribati",
      "fr": "Kiribati",
      "ar": "كيريباتي",
      "tr": "Kiribati",
    },
  ),
  Countrymodel(
    code: "KM",
    names: {
      "en": "Comoros",
      "zh": "科摩罗",
      "hi": "कोमोरोस",
      "es": "Comoras",
      "fr": "Comores",
      "ar": "جزر القمر",
      "tr": "Komorlar",
    },
  ),
  Countrymodel(
    code: "KN",
    names: {
      "en": "Saint Kitts and Nevis",
      "zh": "圣基茨和尼维斯",
      "hi": "सेंट किट्स और नेविस",
      "es": "San Cristóbal y Nieves",
      "fr": "Saint-Christophe-et-Niévès",
      "ar": "سانت كيتس ونيفيس",
      "tr": "Saint Kitts ve Nevis",
    },
  ),
  Countrymodel(
    code: "KP",
    names: {
      "en": "Korea (Democratic People's Republic of)",
      "zh": "朝鲜",
      "hi": "उत्तर कोरिया",
      "es": "Corea del Norte",
      "fr": "Corée du Nord",
      "ar": "كوريا الشمالية",
      "tr": "Kuzey Kore",
    },
  ),
  Countrymodel(
    code: "KR",
    names: {
      "en": "Korea, Republic of",
      "zh": "韩国",
      "hi": "दक्षिण कोरिया",
      "es": "Corea del Sur",
      "fr": "Corée du Sud",
      "ar": "كوريا الجنوبية",
      "tr": "Güney Kore",
    },
  ),
  Countrymodel(
    code: "KW",
    names: {
      "en": "Kuwait",
      "zh": "科威特",
      "hi": "कुवैत",
      "es": "Kuwait",
      "fr": "Koweït",
      "ar": "الكويت",
      "tr": "Kuveyt",
    },
  ),
  Countrymodel(
    code: "KY",
    names: {
      "en": "Cayman Islands",
      "zh": "开曼群岛",
      "hi": "केमैन द्वीपसमूह",
      "es": "Islas Caimán",
      "fr": "Îles Caïmans",
      "ar": "جزر كايمان",
      "tr": "Cayman Adaları",
    },
  ),
  Countrymodel(
    code: "KZ",
    names: {
      "en": "Kazakhstan",
      "zh": "哈萨克斯坦",
      "hi": "कजाखस्तान",
      "es": "Kazajistán",
      "fr": "Kazakhstan",
      "ar": "كازاخستان",
      "tr": "Kazakistan",
    },
  ),
  Countrymodel(
    code: "LA",
    names: {
      "en": "Lao People's Democratic Republic",
      "zh": "老挝",
      "hi": "लाओस",
      "es": "Laos",
      "fr": "Laos",
      "ar": "لاوس",
      "tr": "Laos",
    },
  ),
  Countrymodel(
    code: "LB",
    names: {
      "en": "Lebanon",
      "zh": "黎巴嫩",
      "hi": "लेबनान",
      "es": "Líbano",
      "fr": "Liban",
      "ar": "لبنان",
      "tr": "Lübnan",
    },
  ),
  Countrymodel(
    code: "LC",
    names: {
      "en": "Saint Lucia",
      "zh": "圣卢西亚",
      "hi": "सेंट लूसिया",
      "es": "Santa Lucía",
      "fr": "Sainte-Lucie",
      "ar": "سانت لوسيا",
      "tr": "Saint Lucia",
    },
  ),
  Countrymodel(
    code: "LI",
    names: {
      "en": "Liechtenstein",
      "zh": "列支敦士登",
      "hi": "लिचटेंस्टाइन",
      "es": "Liechtenstein",
      "fr": "Liechtenstein",
      "ar": "ليختنشتاين",
      "tr": "Lihtenştayn",
    },
  ),
  Countrymodel(
    code: "LK",
    names: {
      "en": "Sri Lanka",
      "zh": "斯里兰卡",
      "hi": "श्रीलंका",
      "es": "Sri Lanka",
      "fr": "Sri Lanka",
      "ar": "سريلانكا",
      "tr": "Sri Lanka",
    },
  ),
  Countrymodel(
    code: "LR",
    names: {
      "en": "Liberia",
      "zh": "利比里亚",
      "hi": "लाइबेरिया",
      "es": "Liberia",
      "fr": "Libéria",
      "ar": "ليبيريا",
      "tr": "Liberya",
    },
  ),
  Countrymodel(
    code: "LS",
    names: {
      "en": "Lesotho",
      "zh": "莱索托",
      "hi": "लेसोथो",
      "es": "Lesoto",
      "fr": "Lesotho",
      "ar": "ليسوتو",
      "tr": "Lesotho",
    },
  ),
  Countrymodel(
    code: "LT",
    names: {
      "en": "Lithuania",
      "zh": "立陶宛",
      "hi": "लिथुआनिया",
      "es": "Lituania",
      "fr": "Lituanie",
      "ar": "ليتوانيا",
      "tr": "Litvanya",
    },
  ),
  Countrymodel(
    code: "LU",
    names: {
      "en": "Luxembourg",
      "zh": "卢森堡",
      "hi": "लक्समबर्ग",
      "es": "Luxemburgo",
      "fr": "Luxembourg",
      "ar": "لوكسمبورغ",
      "tr": "Lüksemburg",
    },
  ),
  Countrymodel(
    code: "LV",
    names: {
      "en": "Latvia",
      "zh": "拉脱维亚",
      "hi": "लातविया",
      "es": "Letonia",
      "fr": "Lettonie",
      "ar": "لاتفيا",
      "tr": "Letonya",
    },
  ),
  Countrymodel(
    code: "LY",
    names: {
      "en": "Libya",
      "zh": "利比亚",
      "hi": "लीबिया",
      "es": "Libia",
      "fr": "Libye",
      "ar": "ليبيا",
      "tr": "Libya",
    },
  ),
  Countrymodel(
    code: "MA",
    names: {
      "en": "Morocco",
      "zh": "摩洛哥",
      "hi": "मोरक्को",
      "es": "Marruecos",
      "fr": "Maroc",
      "ar": "المغرب",
      "tr": "Fas",
    },
  ),
  Countrymodel(
    code: "MC",
    names: {
      "en": "Monaco",
      "zh": "摩纳哥",
      "hi": "मोनाको",
      "es": "Mónaco",
      "fr": "Monaco",
      "ar": "موناكو",
      "tr": "Monako",
    },
  ),
  Countrymodel(
    code: "MD",
    names: {
      "en": "Moldova, Republic of",
      "zh": "摩尔多瓦",
      "hi": "मोल्दोवा",
      "es": "Moldavia",
      "fr": "Moldavie",
      "ar": "مولدوفا",
      "tr": "Moldova",
    },
  ),
  Countrymodel(
    code: "ME",
    names: {
      "en": "Montenegro",
      "zh": "黑山",
      "hi": "मोंटेनेग्रो",
      "es": "Montenegro",
      "fr": "Monténégro",
      "ar": "الجبل الأسود",
      "tr": "Karadağ",
    },
  ),
  Countrymodel(
    code: "MF",
    names: {
      "en": "Saint Martin (French part)",
      "zh": "法属圣马丁",
      "hi": "सेंट मार्टिन (फ्रेंच भाग)",
      "es": "San Martín (parte francesa)",
      "fr": "Saint-Martin (partie française)",
      "ar": "سانت مارتن (الجزء الفرنسي)",
      "tr": "Saint Martin (Fransız kısmı)",
    },
  ),
  Countrymodel(
    code: "MG",
    names: {
      "en": "Madagascar",
      "zh": "马达加斯加",
      "hi": "मेडागास्कर",
      "es": "Madagascar",
      "fr": "Madagascar",
      "ar": "مدغشقر",
      "tr": "Madagaskar",
    },
  ),
  Countrymodel(
    code: "MH",
    names: {
      "en": "Marshall Islands",
      "zh": "马绍尔群岛",
      "hi": "मार्शल द्वीपसमूह",
      "es": "Islas Marshall",
      "fr": "Îles Marshall",
      "ar": "جزر مارشال",
      "tr": "Marshall Adaları",
    },
  ),
  Countrymodel(
    code: "MK",
    names: {
      "en": "North Macedonia",
      "zh": "北马其顿",
      "hi": "उत्तरी मैसेडोनिया",
      "es": "Macedonia del Norte",
      "fr": "Macédoine du Nord",
      "ar": "شمال مقدونيا",
      "tr": "Kuzey Makedonya",
    },
  ),
  Countrymodel(
    code: "ML",
    names: {
      "en": "Mali",
      "zh": "马里",
      "hi": "माली",
      "es": "Mali",
      "fr": "Mali",
      "ar": "مالي",
      "tr": "Mali",
    },
  ),
  Countrymodel(
    code: "MM",
    names: {
      "en": "Myanmar",
      "zh": "缅甸",
      "hi": "म्यांमार",
      "es": "Myanmar",
      "fr": "Myanmar",
      "ar": "ميانمار",
      "tr": "Myanmar",
    },
  ),
  Countrymodel(
    code: "MN",
    names: {
      "en": "Mongolia",
      "zh": "蒙古",
      "hi": "मंगोलिया",
      "es": "Mongolia",
      "fr": "Mongolie",
      "ar": "منغوليا",
      "tr": "Moğolistan",
    },
  ),
  Countrymodel(
    code: "MO",
    names: {
      "en": "Macao",
      "zh": "澳门",
      "hi": "मकाओ",
      "es": "Macao",
      "fr": "Macao",
      "ar": "ماكاو",
      "tr": "Makao",
    },
  ),
  Countrymodel(
    code: "MP",
    names: {
      "en": "Northern Mariana Islands",
      "zh": "北马里亚纳群岛",
      "hi": "उत्तरी मारियाना द्वीपसमूह",
      "es": "Islas Marianas del Norte",
      "fr": "Îles Mariannes du Nord",
      "ar": "جزر ماريانا الشمالية",
      "tr": "Kuzey Mariana Adaları",
    },
  ),
  Countrymodel(
    code: "MQ",
    names: {
      "en": "Martinique",
      "zh": "马提尼克",
      "hi": "मार्टीनिक",
      "es": "Martinica",
      "fr": "Martinique",
      "ar": "مارتينيك",
      "tr": "Martinik",
    },
  ),
  Countrymodel(
    code: "MR",
    names: {
      "en": "Mauritania",
      "zh": "毛里塔尼亚",
      "hi": "मॉरिटानिया",
      "es": "Mauritania",
      "fr": "Mauritanie",
      "ar": "موريتانيا",
      "tr": "Moritanya",
    },
  ),
  Countrymodel(
    code: "MS",
    names: {
      "en": "Montserrat",
      "zh": "蒙特塞拉特",
      "hi": "मोंटसेरात",
      "es": "Montserrat",
      "fr": "Montserrat",
      "ar": "مونتسرات",
      "tr": "Montserrat",
    },
  ),
  Countrymodel(
    code: "MT",
    names: {
      "en": " Malta",
      "zh": "马耳他",
      "hi": "माल्टा",
      "es": "Malta",
      "fr": "Malte",
      "ar": "مالطا",
      "tr": "Malta",
    },
  ),
  Countrymodel(
    code: "MU",
    names: {
      "en": "Mauritius",
      "zh": "毛里求斯",
      "hi": "मॉरीशस",
      "es": "Mauricio",
      "fr": "Maurice",
      "ar": "موريشيوس",
      "tr": "Mauritius",
    },
  ),
  Countrymodel(
    code: "MV",
    names: {
      "en": "Maldives",
      "zh": "马尔代夫",
      "hi": "मालदीव",
      "es": "Maldivas",
      "fr": "Maldives",
      "ar": "جزر المالديف",
      "tr": "Maldivler",
    },
  ),
  Countrymodel(
    code: "MW",
    names: {
      "en": "Malawi",
      "zh": "马拉维",
      "hi": "मलावी",
      "es": "Malaui",
      "fr": "Malawi",
      "ar": "مالاوي",
      "tr": "Malavi",
    },
  ),
  Countrymodel(
    code: "MX",
    names: {
      "en": "Mexico",
      "zh": "墨西哥",
      "hi": "मेक्सिको",
      "es": "México",
      "fr": "Mexique",
      "ar": "المكسيك",
      "tr": "Meksika",
    },
  ),
  Countrymodel(
    code: "MY",
    names: {
      "en": "Malaysia",
      "zh": "马来西亚",
      "hi": "मलेशिया",
      "es": "Malasia",
      "fr": "Malaisie",
      "ar": "ماليزيا",
      "tr": "Malezya",
    },
  ),
  Countrymodel(
    code: "MZ",
    names: {
      "en": "Mozambique",
      "zh": "莫桑比克",
      "hi": "मोज़ांबिक",
      "es": "Mozambique",
      "fr": "Mozambique",
      "ar": "موزمبيق",
      "tr": "Mozambik",
    },
  ),
  Countrymodel(
    code: "NA",
    names: {
      "en": "Namibia",
      "zh": "纳米比亚",
      "hi": "नामीबिया",
      "es": "Namibia",
      "fr": "Namibie",
      "ar": "ناميبيا",
      "tr": "Namibya",
    },
  ),
  Countrymodel(
    code: "NC",
    names: {
      "en": "New Caledonia",
      "zh": "新喀里多尼亚",
      "hi": "न्यू कैलेडोनिया",
      "es": "Nueva Caledonia",
      "fr": "Nouvelle-Calédonie",
      "ar": "كاليدونيا الجديدة",
      "tr": "Yeni Kaledonya",
    },
  ),
  Countrymodel(
    code: "NE",
    names: {
      "en": "Niger",
      "zh": "尼日尔",
      "hi": "नाइजर",
      "es": "Níger",
      "fr": "Niger",
      "ar": "النيجر",
      "tr": "Nijer",
    },
  ),
  Countrymodel(
    code: "NF",
    names: {
      "en": "Norfolk Island",
      "zh": "诺福克岛",
      "hi": "नॉरफ़ॉक द्वीप",
      "es": "Isla Norfolk",
      "fr": "Île Norfolk",
      "ar": "جزيرة نورفولك",
      "tr": "Norfolk Adası",
    },
  ),
  Countrymodel(
    code: "NG",
    names: {
      "en": "Nigeria",
      "zh": "尼日利亚",
      "hi": "नाइजीरिया",
      "es": "Nigeria",
      "fr": "Nigéria",
      "ar": "نيجيريا",
      "tr": "Nijerya",
    },
  ),
  Countrymodel(
    code: "NI",
    names: {
      "en": "Nicaragua",
      "zh": "尼加拉瓜",
      "hi": "निकारागुआ",
      "es": "Nicaragua",
      "fr": "Nicaragua",
      "ar": "نيكاراغوا",
      "tr": "Nikaragua",
    },
  ),
  Countrymodel(
    code: "NL",
    names: {
      "en": "Netherlands",
      "zh": "荷兰",
      "hi": "नीदरलैंड",
      "es": "Países Bajos",
      "fr": "Pays-Bas",
      "ar": "هولندا",
      "tr": "Hollanda",
    },
  ),
  Countrymodel(
    code: "NO",
    names: {
      "en": "Norway",
      "zh": "挪威",
      "hi": "नॉर्वे",
      "es": "Noruega",
      "fr": "Norvège",
      "ar": "النرويج",
      "tr": "Norveç",
    },
  ),
  Countrymodel(
    code: "NP",
    names: {
      "en": "Nepal",
      "zh": "尼泊尔",
      "hi": "नेपाल",
      "es": "Nepal",
      "fr": "Népal",
      "ar": "نيبال",
      "tr": "Nepal",
    },
  ),
  Countrymodel(
    code: "NR",
    names: {
      "en": "Nauru",
      "zh": "瑙鲁",
      "hi": "नाउरु",
      "es": "Nauru",
      "fr": "Nauru",
      "ar": "ناورو",
      "tr": "Nauru",
    },
  ),
  Countrymodel(
    code: "NU",
    names: {
      "en": "Niue",
      "zh": "纽埃",
      "hi": "नीयू",
      "es": "Niue",
      "fr": "Niue",
      "ar": "نيوي",
      "tr": "Niue",
    },
  ),
  Countrymodel(
    code: "NZ",
    names: {
      "en": "New Zealand",
      "zh": "新西兰",
      "hi": "न्यूज़ीलैंड",
      "es": "Nueva Zelanda",
      "fr": "Nouvelle-Zélande",
      "ar": "نيوزيلندا",
      "tr": "Yeni Zelanda",
    },
  ),
  Countrymodel(
    code: "OM",
    names: {
      "en": "Oman",
      "zh": "阿曼",
      "hi": "ओमान",
      "es": "Omán",
      "fr": "Oman",
      "ar": "عُمان",
      "tr": "Umman",
    },
  ),
  Countrymodel(
    code: "PA",
    names: {
      "en": "Panama",
      "zh": "巴拿马",
      "hi": "पनामा",
      "es": "Panamá",
      "fr": "Panama",
      "ar": "بنما",
      "tr": "Panama",
    },
  ),
  Countrymodel(
    code: "PE",
    names: {
      "en": "Peru",
      "zh": "秘鲁",
      "hi": "पेरू",
      "es": "Perú",
      "fr": "Pérou",
      "ar": "بيرو",
      "tr": "Peru",
    },
  ),
  Countrymodel(
    code: "PF",
    names: {
      "en": "French Polynesia",
      "zh": "法属波利尼西亚",
      "hi": "फ़्रेंच पोलिनेशिया",
      "es": "Polinesia Francesa",
      "fr": "Polynésie française",
      "ar": "بولينيزيا الفرنسية",
      "tr": "Fransız Polinezyası",
    },
  ),
  Countrymodel(
    code: "PG",
    names: {
      "en": "Papua New Guinea",
      "zh": "巴布亚新几内亚",
      "hi": "पापुआ न्यू गिनी",
      "es": "Papúa Nueva Guinea",
      "fr": "Papouasie-Nouvelle-Guinée",
      "ar": "بابوا غينيا الجديدة",
      "tr": "Papua Yeni Gine",
    },
  ),
  Countrymodel(
    code: "PH",
    names: {
      "en": "Philippines",
      "zh": "菲律宾",
      "hi": "फ़िलीपींस",
      "es": "Filipinas",
      "fr": "Philippines",
      "ar": "الفلبين",
      "tr": "Filipinler",
    },
  ),
  Countrymodel(
    code: "PK",
    names: {
      "en": "Pakistan",
      "zh": "巴基斯坦",
      "hi": "पाकिस्तान",
      "es": "Pakistán",
      "fr": "Pakistan",
      "ar": "باكستان",
      "tr": "Pakistan",
    },
  ),
  Countrymodel(
    code: "PL",
    names: {
      "en": "Poland",
      "zh": "波兰",
      "hi": "पोलैंड",
      "es": "Polonia",
      "fr": "Pologne",
      "ar": "بولندا",
      "tr": "Polonya",
    },
  ),
  Countrymodel(
    code: "PM",
    names: {
      "en": "Saint Pierre and Miquelon",
      "zh": "圣皮埃尔和密克隆",
      "hi": "सेंट पियरे और मिकेलॉन",
      "es": "San Pedro y Miquelón",
      "fr": "Saint-Pierre-et-Miquelon",
      "ar": "سان بيير وميكلون",
      "tr": "Saint Pierre ve Miquelon",
    },
  ),
  Countrymodel(
    code: "PN",
    names: {
      "en": "Pitcairn",
      "zh": "皮特凯恩群岛",
      "hi": "पिटकैर्न द्वीपसमूह",
      "es": "Islas Pitcairn",
      "fr": "Îles Pitcairn",
      "ar": "جزر بيتكيرن",
      "tr": "Pitcairn Adaları",
    },
  ),
  Countrymodel(
    code: "PR",
    names: {
      "en": "Puerto Rico",
      "zh": "波多黎各",
      "hi": "प्यूर्टो रिको",
      "es": "Puerto Rico",
      "fr": "Porto Rico",
      "ar": "بورتوريكو",
      "tr": "Porto Riko",
    },
  ),
  Countrymodel(
    code: "PS",
    names: {
      "en": "Palestine, State of",
      "zh": "巴勒斯坦",
      "hi": "फ़िलिस्तीन",
      "es": "Palestina",
      "fr": "Palestine",
      "ar": "فلسطين",
      "tr": "Filistin",
    },
  ),
  Countrymodel(
    code: "PT",
    names: {
      "en": "Portugal",
      "zh": "葡萄牙",
      "hi": "पुर्तगाल",
      "es": "Portugal",
      "fr": "Portugal",
      "ar": "البرتغal",
      "tr": "Portekiz",
    },
  ),
  Countrymodel(
    code: "PW",
    names: {
      "en": "Palau",
      "zh": "帕劳",
      "hi": "पलाऊ",
      "es": "Palaos",
      "fr": "Palaos",
      "ar": "بالاو",
      "tr": "Palau",
    },
  ),
  Countrymodel(
    code: "PY",
    names: {
      "en": "Paraguay",
      "zh": "巴拉圭",
      "hi": "पैराग्वे",
      "es": "Paraguay",
      "fr": "Paraguay",
      "ar": "باراغواي",
      "tr": "Paraguay",
    },
  ),
  Countrymodel(
    code: "QA",
    names: {
      "en": "Qatar",
      "zh": "卡塔尔",
      "hi": "क़तर",
      "es": "Catar",
      "fr": "Qatar",
      "ar": "قطر",
      "tr": "Katar",
    },
  ),
  Countrymodel(
    code: "RE",
    names: {
      "en": "Réunion",
      "zh": "留尼汪",
      "hi": "रेयूनियन",
      "es": "Reunión",
      "fr": "La Réunion",
      "ar": "لا ريونيون",
      "tr": "Réunion",
    },
  ),
  Countrymodel(
    code: "RO",
    names: {
      "en": "Romania",
      "zh": "罗马尼亚",
      "hi": "रोमानिया",
      "es": "Rumania",
      "fr": "Roumanie",
      "ar": "رومانيا",
      "tr": "Romanya",
    },
  ),
  Countrymodel(
    code: "RS",
    names: {
      "en": "Serbia",
      "zh": "塞尔维亚",
      "hi": "सर्बिया",
      "es": "Serbia",
      "fr": "Serbie",
      "ar": "صربيا",
      "tr": "Sırbistan",
    },
  ),
  Countrymodel(
    code: "RU",
    names: {
      "en": "Russian Federation",
      "zh": "俄罗斯联邦",
      "hi": "रूस",
      "es": "Rusia",
      "fr": "Russie",
      "ar": "روسيا",
      "tr": "Rusya",
    },
  ),
  Countrymodel(
    code: "RW",
    names: {
      "en": "Rwanda",
      "zh": "卢旺达",
      "hi": "रवांडा",
      "es": "Ruanda",
      "fr": "Rwanda",
      "ar": "رواندا",
      "tr": "Ruanda",
    },
  ),
  Countrymodel(
    code: "SA",
    names: {
      "en": "Saudi Arabia",
      "zh": "沙特阿拉伯",
      "hi": "सऊदी अरब",
      "es": "Arabia Saudita",
      "fr": "Arabie saoudite",
      "ar": "المملكة العربية السعودية",
      "tr": "Suudi Arabistan",
    },
  ),
  Countrymodel(
    code: "SB",
    names: {
      "en": "Solomon Islands",
      "zh": "所罗门群岛",
      "hi": "सोलोमन द्वीपसमूह",
      "es": "Islas Salomón",
      "fr": "Îles Salomon",
      "ar": "جزر سليمان",
      "tr": "Solomon Adaları",
    },
  ),
  Countrymodel(
    code: "SC",
    names: {
      "en": "Seychelles",
      "zh": "塞舌尔",
      "hi": "सेशेल्स",
      "es": "Seychelles",
      "fr": "Seychelles",
      "ar": "سيشل",
      "tr": "Seyşeller",
    },
  ),
  Countrymodel(
    code: "SD",
    names: {
      "en": "Sudan",
      "zh": "苏丹",
      "hi": "सूडान",
      "es": "Sudán",
      "fr": "Soudan",
      "ar": "السودان",
      "tr": "Sudan",
    },
  ),
  Countrymodel(
    code: "SE",
    names: {
      "en": "Sweden",
      "zh": "瑞典",
      "hi": "स्वीडन",
      "es": "Suecia",
      "fr": "Suède",
      "ar": "السويد",
      "tr": "İsveç",
    },
  ),
  Countrymodel(
    code: "SG",
    names: {
      "en": "Singapore",
      "zh": "新加坡",
      "hi": "सिंगापुर",
      "es": "Singapur",
      "fr": "Singapour",
      "ar": "سنغافورة",
      "tr": "Singapur",
    },
  ),
  Countrymodel(
    code: "SH",
    names: {
      "en": "Saint Helena, Ascension and Tristan da Cunha",
      "zh": "圣赫勒拿、阿森松和特里斯坦-达库尼亚",
      "hi": "सेंट हेलेना, अscension और ट्रिस्टन दा कुन्हा",
      "es": "Santa Elena, Ascensión y Tristán de Acuña",
      "fr": "Sainte-Hélène, Ascension et Tristan da Cunha",
      "ar": "سانت هيلينا وأسينشين وتريستان دا كونا",
      "tr": "Saint Helena, Ascension ve Tristan da Cunha",
    },
  ),
  Countrymodel(
    code: "SI",
    names: {
      "en": "Slovenia",
      "zh": "斯洛文尼亚",
      "hi": "स्लोवेनिया",
      "es": "Eslovenia",
      "fr": "Slovénie",
      "ar": "سلوفينيا",
      "tr": "Slovenya",
    },
  ),
  Countrymodel(
    code: "SJ",
    names: {
      "en": "Svalbard and Jan Mayen",
      "zh": "斯瓦尔巴和扬马延",
      "hi": "स्वालबार्ड और जान मायेन",
      "es": "Svalbard y Jan Mayen",
      "fr": "Svalbard et Jan Mayen",
      "ar": "سفالبارد ويان ماين",
      "tr": "Svalbard ve Jan Mayen",
    },
  ),
  Countrymodel(
    code: "SK",
    names: {
      "en": "Slovakia",
      "zh": "斯洛伐克",
      "hi": "स्लोवाकिया",
      "es": "Eslovaquia",
      "fr": "Slovaquie",
      "ar": "سلوفاكيا",
      "tr": "Slovakya",
    },
  ),
  Countrymodel(
    code: "SL",
    names: {
      "en": "Sierra Leone",
      "zh": "塞拉利昂",
      "hi": "सिएरा लियोन",
      "es": "Sierra Leona",
      "fr": "Sierra Leone",
      "ar": "سيراليون",
      "tr": "Sierra Leone",
    },
  ),
  Countrymodel(
    code: "SM",
    names: {
      "en": "San Marino",
      "zh": "圣马力诺",
      "hi": "सैन मेरीनो",
      "es": "San Marino",
      "fr": "Saint-Marin",
      "ar": "سان مارينو",
      "tr": "San Marino",
    },
  ),
  Countrymodel(
    code: "SN",
    names: {
      "en": "Senegal",
      "zh": "塞内加尔",
      "hi": "सेनेगल",
      "es": "Senegal",
      "fr": "Sénégal",
      "ar": "السنغال",
      "tr": "Senegal",
    },
  ),
  Countrymodel(
    code: "SO",
    names: {
      "en": "Somalia",
      "zh": "索马里",
      "hi": "सोमालिया",
      "es": "Somalia",
      "fr": "Somalie",
      "ar": "الصومال",
      "tr": "Somali",
    },
  ),
  Countrymodel(
    code: "SR",
    names: {
      "en": "Suriname",
      "zh": "苏里南",
      "hi": "सूरीनाम",
      "es": "Surinam",
      "fr": "Suriname",
      "ar": "سورينام",
      "tr": "Surinam",
    },
  ),
  Countrymodel(
    code: "SS",
    names: {
      "en": "South Sudan",
      "zh": "南苏丹",
      "hi": "दक्षिण सूडान",
      "es": "Sudán del Sur",
      "fr": "Soudan du Sud",
      "ar": "جنوب السودان",
      "tr": "Güney Sudan",
    },
  ),
  Countrymodel(
    code: "ST",
    names: {
      "en": "Sao Tome and Principe",
      "zh": "圣多美和普林西比",
      "hi": "साओ टोम और प्रिंसिपे",
      "es": "Santo Tomé y Príncipe",
      "fr": "Sao Tomé-et-Principe",
      "ar": "ساو تومي وبرينسيب",
      "tr": "São Tomé ve Príncipe",
    },
  ),
  Countrymodel(
    code: "SV",
    names: {
      "en": "El Salvador",
      "zh": "萨尔瓦多",
      "hi": "अल साल्वाडोर",
      "es": "El Salvador",
      "fr": "Salvador",
      "ar": "السلفادور",
      "tr": "El Salvador",
    },
  ),
  Countrymodel(
    code: "SX",
    names: {
      "en": "Sint Maarten (Dutch part)",
      "zh": "荷属圣马丁",
      "hi": "सिंट मार्टेन (डच भाग)",
      "es": "Sint Maarten (parte neerlandesa)",
      "fr": "Saint-Martin (partie néerlandaise)",
      "ar": "سينت مارتن (الجزء الهولندي)",
      "tr": "Sint Maarten (Hollanda kısmı)",
    },
  ),
  Countrymodel(
    code: "SY",
    names: {
      "en": "Syrian Arab Republic",
      "zh": "叙利亚",
      "hi": "सीरिया",
      "es": "Siria",
      "fr": "Syrie",
      "ar": "سوريا",
      "tr": "Suriye",
    },
  ),
  Countrymodel(
    code: "SZ",
    names: {
      "en": "Eswatini",
      "zh": "斯威士兰",
      "hi": "एस्वातीनी",
      "es": "Esuatini",
      "fr": "Eswatini",
      "ar": "إسواتيني",
      "tr": "Esvatini",
    },
  ),
  Countrymodel(
    code: "TC",
    names: {
      "en": "Turks and Caicos Islands",
      "zh": "特克斯和凯科斯群岛",
      "hi": "टर्क्स और कैकोस द्वीपसमूह",
      "es": "Islas Turcas y Caicos",
      "fr": "Îles Turques-et-Caïques",
      "ar": "جزر توركس وكايكوس",
      "tr": "Turks ve Caicos Adaları",
    },
  ),
  Countrymodel(
    code: "TD",
    names: {
      "en": "Chad",
      "zh": "乍得",
      "hi": "चाड",
      "es": "Chad",
      "fr": "Tchad",
      "ar": "تشاد",
      "tr": "Çad",
    },
  ),
  Countrymodel(
    code: "TF",
    names: {
      "en": "French Southern Territories",
      "zh": "法属南部领地",
      "hi": "फ़्रेंच दक्षिणी क्षेत्र",
      "es": "Tierras Australes Francesas",
      "fr": "Terres australes françaises",
      "ar": "الأراضي الفرنسية الجنوبية",
      "tr": "Fransız Güney Toprakları",
    },
  ),
  Countrymodel(
    code: "TG",
    names: {
      "en": "Togo",
      "zh": "多哥",
      "hi": "टोगो",
      "es": "Togo",
      "fr": "Togo",
      "ar": "توغو",
      "tr": "Togo",
    },
  ),
  Countrymodel(
    code: "TH",
    names: {
      "en": "Thailand",
      "zh": "泰国",
      "hi": "थाईलैंड",
      "es": "Tailandia",
      "fr": "Thaïlande",
      "ar": "تايلاند",
      "tr": "Tayland",
    },
  ),
  Countrymodel(
    code: "TJ",
    names: {
      "en": "Tajikistan",
      "zh": "塔吉克斯坦",
      "hi": "ताजिकिस्तान",
      "es": "Tayikistán",
      "fr": "Tadjikistan",
      "ar": "طاجيكستان",
      "tr": "Tacikistan",
    },
  ),
  Countrymodel(
    code: "TK",
    names: {
      "en": "Tokelau",
      "zh": "托克劳",
      "hi": "टोकेलau",
      "es": "Tokelau",
      "fr": "Tokelau",
      "ar": "توكيلau",
      "tr": "Tokelau",
    },
  ),
  Countrymodel(
    code: "TL",
    names: {
      "en": "Timor-Leste",
      "zh": "东帝汶",
      "hi": "तिमोर-लेस्ते",
      "es": "Timor-Leste",
      "fr": "Timor oriental",
      "ar": "تيمور الشرقية",
      "tr": "Doğu Timor",
    },
  ),
  Countrymodel(
    code: "TM",
    names: {
      "en": "Turkmenistan",
      "zh": "土库曼斯坦",
      "hi": "तुर्कमेनिस्तान",
      "es": "Turkmenistán",
      "fr": "Turkménistan",
      "ar": "تركمانستان",
      "tr": "Türkmenistan",
    },
  ),
  Countrymodel(
    code: "TN",
    names: {
      "en": "Tunisia",
      "zh": "突尼斯",
      "hi": "ट्यूनीशिया",
      "es": "Túnez",
      "fr": "Tunisie",
      "ar": "تونس",
      "tr": "Tunus",
    },
  ),
  Countrymodel(
    code: "TO",
    names: {
      "en": "Tonga",
      "zh": "汤加",
      "hi": "टोंगा",
      "es": "Tonga",
      "fr": "Tonga",
      "ar": "تونغا",
      "tr": "Tonga",
    },
  ),
  Countrymodel(
    code: "TR",
    names: {
      "en": "Türkiye",
      "zh": "土耳其",
      "hi": "तुर्की",
      "es": "Turquía",
      "fr": "Turquie",
      "ar": "تركيا",
      "tr": "Türkiye",
    },
  ),
  Countrymodel(
    code: "TT",
    names: {
      "en": "Trinidad and Tobago",
      "zh": "特立尼达和多巴哥",
      "hi": "त्रिनिदाद और टोबैगो",
      "es": "Trinidad y Tobago",
      "fr": "Trinité-et-Tobago",
      "ar": "ترينيداد وتوباغو",
      "tr": "Trinidad ve Tobago",
    },
  ),
  Countrymodel(
    code: "TV",
    names: {
      "en": "Tuvalu",
      "zh": "图瓦卢",
      "hi": "तुवालू",
      "es": "Tuvalu",
      "fr": "Tuvalu",
      "ar": "توفالو",
      "tr": "Tuvalu",
    },
  ),
  Countrymodel(
    code: "TW",
    names: {
      "en": "Taiwan, Province of China",
      "zh": "中国台湾省",
      "hi": "ताइवान",
      "es": "Taiwán (Provincia de China)",
      "fr": "Taïwan (province de Chine)",
      "ar": "تايوان (مقاطعة صينية)",
      "tr": "Tayvan (Çin'in bir eyaleti)",
    },
  ),
  Countrymodel(
    code: "TZ",
    names: {
      "en": "Tanzania, United Republic of",
      "zh": "坦桑尼亚",
      "hi": "तंज़ानिया",
      "es": "Tanzania",
      "fr": "Tanzanie",
      "ar": "تنزانيا",
      "tr": "Tanzanya",
    },
  ),
  Countrymodel(
    code: "UA",
    names: {
      "en": "Ukraine",
      "zh": "乌克兰",
      "hi": "यूक्रेन",
      "es": "Ucrania",
      "fr": "Ukraine",
      "ar": "أوكرانيا",
      "tr": "Ukrayna",
    },
  ),
  Countrymodel(
    code: "UG",
    names: {
      "en": "Uganda",
      "zh": "乌干达",
      "hi": "युगांडा",
      "es": "Uganda",
      "fr": "Ouganda",
      "ar": "أوغندا",
      "tr": "Uganda",
    },
  ),
  Countrymodel(
    code: "UM",
    names: {
      "en": "United States Minor Outlying Islands",
      "zh": "美国本土外小岛屿",
      "hi": "संयुक्त राज्य अमेरिका के छोटे दूरस्थ द्वीपसमूह",
      "es": "Islas Ultramarinas Menores de Estados Unidos",
      "fr": "Îles mineures éloignées des États-Unis",
      "ar": "جزر الولايات المتحدة الصغيرة النائية",
      "tr": "Amerika Birleşik Devletleri Küçük Dış Adaları",
    },
  ),
  Countrymodel(
    code: "US",
    names: {
      "en": "United States of America",
      "zh": "美利坚合众国",
      "hi": "संयुक्त राज्य अमेरिका",
      "es": "Estados Unidos de América",
      "fr": "États-Unis d’Amérique",
      "ar": "الولايات المتحدة الأمريكية",
      "tr": "Amerika Birleşik Devletleri",
    },
  ),
  Countrymodel(
    code: "UY",
    names: {
      "en": "Uruguay",
      "zh": "乌拉圭",
      "hi": "उरुग्वे",
      "es": "Uruguay",
      "fr": "Uruguay",
      "ar": "أوروغواي",
      "tr": "Uruguay",
    },
  ),
  Countrymodel(
    code: "UZ",
    names: {
      "en": "Uzbekistan",
      "zh": "乌兹别克斯坦",
      "hi": "उज़्बेकिस्तान",
      "es": "Uzbekistán",
      "fr": "Ouzbékistan",
      "ar": "أوزبكستان",
      "tr": "Özbekistan",
    },
  ),
  Countrymodel(
    code: "VA",
    names: {
      "en": "Holy See",
      "zh": "梵蒂冈",
      "hi": "वेटिकन सिटी",
      "es": "Santa Sede",
      "fr": "Saint-Siège",
      "ar": "الكرسي الرسولي",
      "tr": "Vatikan",
    },
  ),
  Countrymodel(
    code: "VC",
    names: {
      "en": "Saint Vincent and the Grenadines",
      "zh": "圣文森特和格林纳丁斯",
      "hi": "सेंट विंसेंट और ग्रेनाडाइंस",
      "es": "San Vicente y las Granadinas",
      "fr": "Saint-Vincent-et-les-Grenadines",
      "ar": "سانت فنسنت والغرينادين",
      "tr": "Saint Vincent ve Grenadinler",
    },
  ),
  Countrymodel(
    code: "VE",
    names: {
      "en": "Venezuela (Bolivarian Republic of)",
      "zh": "委内瑞拉",
      "hi": "वेनेज़ुएला",
      "es": "Venezuela",
      "fr": "Venezuela",
      "ar": "فنزويلا",
      "tr": "Venezuela",
    },
  ),
  Countrymodel(
    code: "VG",
    names: {
      "en": "Virgin Islands (British)",
      "zh": "英属维尔京群岛",
      "hi": "ब्रिटिश वर्जिन द्वीपसमूह",
      "es": "Islas Vírgenes Británicas",
      "fr": "Îles Vierges britanniques",
      "ar": "جزر العذراء البريطانية",
      "tr": "Britanya Virjin Adaları",
    },
  ),
  Countrymodel(
    code: "VI",
    names: {
      "en": "Virgin Islands (U.S.)",
      "zh": "美属维尔京群岛",
      "hi": "अमेरिकी वर्जिन द्वीपसमूह",
      "es": "Islas Vírgenes de los Estados Unidos",
      "fr": "Îles Vierges des États-Unis",
      "ar": "جزر العذراء الأمريكية",
      "tr": "ABD Virjin Adaları",
    },
  ),
  Countrymodel(
    code: "VN",
    names: {
      "en": "Viet Nam",
      "zh": "越南",
      "hi": "वियतनाम",
      "es": "Vietnam",
      "fr": "Viêt Nam",
      "ar": "فيتنام",
      "tr": "Vietnam",
    },
  ),
  Countrymodel(
    code: "VU",
    names: {
      "en": "Vanuatu",
      "zh": "瓦努阿图",
      "hi": "वनुआतु",
      "es": "Vanuatu",
      "fr": "Vanuatu",
      "ar": "فانواتو",
      "tr": "Vanuatu",
    },
  ),
  Countrymodel(
    code: "WF",
    names: {
      "en": "Wallis and Futuna",
      "zh": "瓦利斯和富图纳",
      "hi": "वालिस और फ़्यूचूना",
      "es": "Wallis y Futuna",
      "fr": "Wallis-et-Futuna",
      "ar": "واليس وفوتونا",
      "tr": "Wallis ve Futuna",
    },
  ),
  Countrymodel(
    code: "WS",
    names: {
      "en": "Samoa",
      "zh": "萨摩亚",
      "hi": "समोआ",
      "es": "Samoa",
      "fr": "Samoa",
      "ar": "ساموا",
      "tr": "Samoa",
    },
  ),
  Countrymodel(
    code: "YE",
    names: {
      "en": "Yemen",
      "zh": "也门",
      "hi": "यमन",
      "es": "Yemen",
      "fr": "Yémen",
      "ar": "اليمن",
      "tr": "Yemen",
    },
  ),
  Countrymodel(
    code: "YT",
    names: {
      "en": "Mayotte",
      "zh": "马约特",
      "hi": "मायोट",
      "es": "Mayotte",
      "fr": "Mayotte",
      "ar": "مايوت",
      "tr": "Mayotte",
    },
  ),
  Countrymodel(
    code: "ZA",
    names: {
      "en": "South Africa",
      "zh": "南非",
      "hi": "दक्षिण अफ़्रीका",
      "es": "Sudáfrica",
      "fr": "Afrique du Sud",
      "ar": "جنوب أفريقيا",
      "tr": "Güney Afrika",
    },
  ),
  Countrymodel(
    code: "ZM",
    names: {
      "en": "Zambia",
      "zh": "赞比亚",
      "hi": "ज़ाम्बिया",
      "es": "Zambia",
      "fr": "Zambie",
      "ar": "زامبيا",
      "tr": "Zambiya",
    },
  ),
  Countrymodel(
    code: "ZW",
    names: {
      "en": "Zimbabwe",
      "zh": "津巴布韦",
      "hi": "ज़िम्बाब्वे",
      "es": "Zimbabue",
      "fr": "Zimbabwe",
      "ar": "زيمبابوي",
      "tr": "Zimbabve",
    },
  ),
];
